-- Таблица пользователей
CREATE TABLE IF NOT EXISTS users (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- автоинкрементный ID
    email VARCHAR(255) NOT NULL,                         -- email пользователя
    login VARCHAR(255) NOT NULL,                         -- логин пользователя
    name VARCHAR(255),                                   -- имя пользователя
    birthday DATE                                       -- дата рождения
);

-- Таблица рейтингов MPA
CREATE TABLE IF NOT EXISTS mpa (
    id INT PRIMARY KEY,           -- ID рейтинга
    name VARCHAR(10) NOT NULL     -- название рейтинга
);

-- Таблица жанров фильмов
CREATE TABLE IF NOT EXISTS genres (
    id INT PRIMARY KEY,           -- ID жанра
    name VARCHAR(50) NOT NULL     -- название жанра
);

-- Таблица фильмов
CREATE TABLE IF NOT EXISTS films (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- автоинкрементный ID фильма
    name VARCHAR(255) NOT NULL,                          -- название фильма
    description VARCHAR(1024),                           -- описание фильма
    release_date DATE CHECK (release_date >= '1895-12-28'), -- дата релиза
    duration INT NOT NULL,                               -- продолжительность в минутах
    mpa_rating_id INT REFERENCES mpa(id)                -- рейтинг MPA (внешний ключ)
);

-- Таблица связи фильмов и жанров (M:N)
CREATE TABLE IF NOT EXISTS film_genres (
    film_id INT REFERENCES films(id) ON DELETE CASCADE, -- ID фильма
    genre_id INT REFERENCES genres(id),                 -- ID жанра
    PRIMARY KEY (film_id, genre_id)                     -- составной первичный ключ
);

-- Таблица лайков фильмов пользователями (M:N)
CREATE TABLE IF NOT EXISTS film_likes (
    film_id INT REFERENCES films(id) ON DELETE CASCADE, -- ID фильма
    user_id INT REFERENCES users(id) ON DELETE CASCADE, -- ID пользователя
    PRIMARY KEY (film_id, user_id)                      -- составной первичный ключ
);

-- Таблица дружбы пользователей
CREATE TABLE IF NOT EXISTS user_friends (
    user_id INT REFERENCES users(id) ON DELETE CASCADE,   -- кто отправил заявку
    friend_id INT REFERENCES users(id) ON DELETE CASCADE, -- получатель заявки
    status VARCHAR(20) NOT NULL CHECK (status IN ('REQUESTED','CONFIRMED')), -- статус дружбы
    PRIMARY KEY (user_id, friend_id)                     -- составной первичный ключ
);